CREATE TABLE "PROJECT"."CART_TBL" 
   ("CART_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CART_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CART_IMG" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CART_TBL_PK" PRIMARY KEY ("CART_ID"),
	 CONSTRAINT "CART_TBL_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "PROJECT"."MEMBER_TBL" ("ID") ENABLE
	  );